steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://jhdb-cms_cloudbuild/server-creds-prod.json', './server/server-creds.json']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://jhdb-cms_cloudbuild/client-creds-prod.json', './client/client-creds.json']
- name: "gcr.io/cloud-builders/npm"
  args: ["install"]
- name: "gcr.io/cloud-builders/npm"
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--version", "beta", "--no-promote"]
timeout: "1600s"